catalogMode: prefer
cleanupUnusedCatalogs: true
ignoreWorkspaceRootCheck: true
shellEmulator: true

trustPolicy: no-downgrade
allowBuilds:
  esbuild: true
  lightningcss: true
  simple-git-hooks: true

trustPolicyExclude:
  - semver@6.3.1

overrides:
  solid-js: ^1.9.15

packages:
  - apps/*
  - packages/*

catalogs:
  dev:
    '@types/node': ^26.2.0
    nano-staged: ^1.0.2
    oxfmt: ^0.67.0
    oxlint: ~1.79.0
    simple-git-hooks: ^2.14.0
    turbo: ^2.10.12
    typescript: ^6.0.3
